server:
  port: 8500
spring:
  application:
    name: txlcn-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka
    fetch-registry: false #不拉取服务列表
    register-with-eureka: false #不注册自己